import nx from "@nx/eslint-plugin";
import sonarjs from "eslint-plugin-sonarjs";
import security from "eslint-plugin-security";
import importX from "eslint-plugin-import-x";
import n from "eslint-plugin-n";
import prettierConfig from "eslint-config-prettier";

export default [
  ...nx.configs["flat/base"],
  ...nx.configs["flat/typescript"],
  ...nx.configs["flat/javascript"],
  sonarjs.configs.recommended,
  security.configs.recommended,
  importX.flatConfigs.recommended,
  importX.flatConfigs.typescript,
  {
    settings: {
      "import-x/resolver": {
        typescript: true,
      },
    },
    rules: {
      // Off by default in import-x's recommended config (expensive); ADR-00009
      // calls this out specifically for monorepo circular-dependency detection.
      "import-x/no-cycle": "error",
      // Unreliable with CJS/ESM interop (false positives on packages like
      // @nx/eslint-plugin and react) — tsc already checks import correctness
      // more reliably using real type information.
      "import-x/default": "off",
      "import-x/no-named-as-default-member": "off",
      "import-x/no-named-as-default": "off",
    },
  },
  {
    ignores: ["**/dist", "**/out-tsc", "**/test-output"],
  },
  {
    plugins: { n },
    rules: {
      // ADR-00013: env vars must be read through a package's own
      // createEnvGetter-based getter, never process.env directly — so
      // access to a given secret follows the import graph (only code that
      // imports packages/db can reach DATABASE_URL) instead of being
      // ambient/global by default. See the exception below for the one
      // file that's actually allowed to touch process.env.
      "n/no-process-env": "error",
    },
  },
  {
    // The createEnvGetter implementation is the only application/library
    // code allowed to touch process.env directly — everything else,
    // including packages/db's and packages/auth's own env.ts files, goes
    // through it. Test files that manipulate process.env to exercise
    // validation are also legitimate (testing the env-parsing behavior
    // itself, not bypassing it), and tooling config files (e.g.
    // playwright.config.mts's own process.env.CI check) aren't part of the
    // app/package runtime this rule is about.
    files: [
      "**/create-env-getter.ts",
      "**/*.spec.ts",
      "**/*.test.ts",
      "**/playwright.config.mts",
    ],
    rules: {
      "n/no-process-env": "off",
    },
  },
  {
    // Auto-generated by Next.js ("This file should not be edited") and
    // gitignored (not committed). Nx's `typegen` target (a `dependsOn` of
    // `lint`/`typecheck`) regenerates it before either runs, so this is
    // mostly defense in depth — e.g. an IDE invoking `eslint` directly,
    // bypassing Nx's dependency graph, on a checkout where nothing has
    // triggered typegen yet.
    files: ["**/next-env.d.ts"],
    rules: {
      "import-x/no-unresolved": "off",
    },
  },
  {
    files: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"],
    rules: {
      "@nx/enforce-module-boundaries": [
        "error",
        {
          enforceBuildableLibDependency: true,
          allow: ["^.*/eslint(\\.base)?\\.config\\.[cm]?[jt]s$"],
          depConstraints: [
            {
              sourceTag: "*",
              onlyDependOnLibsWithTags: ["*"],
            },
          ],
        },
      ],
    },
  },
  {
    files: [
      "**/*.ts",
      "**/*.tsx",
      "**/*.cts",
      "**/*.mts",
      "**/*.js",
      "**/*.jsx",
      "**/*.cjs",
      "**/*.mjs",
    ],
    // Override or add rules here
    rules: {},
  },
  // Must stay last — disables ESLint stylistic rules that would conflict
  // with Prettier's formatting decisions.
  prettierConfig,
];
