#!/usr/bin/env bash
# Churn × complexity hotspot analysis — files that are both frequently
# changed AND complex are where real risk concentrates (a complex file
# nobody ever touches is low-priority; a complex file changed constantly
# is where bugs and maintenance pain actually happen). This is the
# technique behind tools like CodeScene/code-maat, done here with what we
# already have: git history for churn, ESLint's own `complexity` rule
# (forced to threshold 0 via --rule, so it reports every function's real
# complexity instead of only violations) for the complexity side. No new
# runtime dependency (no Java/code-maat, no Ruby/churn_vs_complexity).
#
# Always exits 0 — informational, like every other section in
# repo-health.sh. Run standalone (`pnpm run hotspots`) or as part of
# `pnpm run health`.

set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

WINDOW_DAYS="${HOTSPOT_WINDOW_DAYS:-180}"
TOP_N="${HOTSPOT_TOP_N:-20}"

echo "Churn × complexity hotspots (last ${WINDOW_DAYS} days, top ${TOP_N})"
echo

# Real source only: excludes build output, generated files (schema.ts is
# regenerated by Better Auth's CLI, *.d.ts are ambient declarations with no
# function bodies to measure), tooling config, and tests (churn/complexity
# of test files isn't the refactoring-priority signal this is for).
mapfile -t FILES < <(
  find apps packages -type f \( -name "*.ts" -o -name "*.tsx" \) \
    -not -path "*/node_modules/*" \
    -not -path "*/.next/*" \
    -not -path "*/dist/*" \
    -not -path "*/out-tsc/*" \
    -not -name "*.spec.ts" -not -name "*.spec.tsx" \
    -not -name "*.test.ts" -not -name "*.test.tsx" \
    -not -name "*.d.ts" \
    -not -name "schema.ts" \
    -not -name "drizzle.config.ts" \
    | sort
)

if [ "${#FILES[@]}" -eq 0 ]; then
  echo "No source files found — nothing to analyze."
  exit 0
fi

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

# --- Churn: commits touching each file in the window ---
git log --since="${WINDOW_DAYS} days ago" --format=format: --name-only -- "${FILES[@]}" 2>/dev/null \
  | grep -v '^$' \
  | sort | uniq -c | sort -rn \
  > "$TMP_DIR/churn.txt"

# --- Complexity: sum of every function's cyclomatic complexity per file ---
# threshold forced to 0 so every function reports (not just violations).
if ! command -v jq >/dev/null 2>&1; then
  echo "jq not installed locally — skipped. See https://jqlang.org/"
  exit 0
fi

pnpm exec eslint --rule '{"complexity": ["warn", 0]}' --format json "${FILES[@]}" 2>/dev/null \
  | jq -r '
      .[] | .filePath as $f | .messages[]
      | select(.ruleId == "complexity")
      | [$f, (.message | capture("complexity of (?<n>[0-9]+)").n)]
      | @tsv
    ' > "$TMP_DIR/complexity-raw.tsv" || true

awk -F'\t' -v root="$PWD/" '
  { file = $1; gsub(root, "", file); complexity[file] += $2 }
  END { for (f in complexity) print complexity[f], f }
' "$TMP_DIR/complexity-raw.tsv" | sort -rn > "$TMP_DIR/complexity.txt"

# --- Join churn + complexity by file path, score = churn × complexity ---
awk '{ churn[$2] = $1 } END { for (f in churn) print f, churn[f] }' "$TMP_DIR/churn.txt" > "$TMP_DIR/churn-by-file.txt"

python3 - "$TMP_DIR/churn-by-file.txt" "$TMP_DIR/complexity.txt" "$TOP_N" <<'PYEOF'
import sys

churn_file, complexity_file, top_n = sys.argv[1], sys.argv[2], int(sys.argv[3])

churn = {}
with open(churn_file) as f:
    for line in f:
        parts = line.rsplit(" ", 1)
        if len(parts) == 2:
            path, count = parts
            churn[path.strip()] = int(count.strip())

complexity = {}
with open(complexity_file) as f:
    for line in f:
        parts = line.strip().split(" ", 1)
        if len(parts) == 2:
            score, path = parts
            complexity[path.strip()] = int(score)

files = set(churn) | set(complexity)
rows = []
for f in files:
    c = churn.get(f, 0)
    x = complexity.get(f, 0)
    rows.append((c * x, c, x, f))

rows.sort(reverse=True)

if not rows or rows[0][0] == 0:
    print("No files with both churn and complexity data in this window — nothing to rank yet.")
    sys.exit(0)

print(f"{'Score':>8}  {'Churn':>6}  {'Complexity':>10}  File")
for score, c, x, f in rows[:top_n]:
    if score == 0:
        continue
    print(f"{score:>8}  {c:>6}  {x:>10}  {f}")
PYEOF

echo
echo "Score = commits touching the file × summed cyclomatic complexity of its functions."
echo "High on both = real refactoring priority, not just 'complex' or just 'busy'."
